version: '3.1'

services:

  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DATABASE_DB}
  web:
    network_mode: "host"
    image: financial-transactions-app
    restart: always
    ports:
      - 4000:4000
    environment:
      APP_PORT: 4000
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_HOST: localhost

    depends_on:
      - database